Add shortcut for messaing semconv messaging.operation.send
open-telemetry/opentelemetry-go pull request #1215
Opened 2020-09-30 06:41 UTC by hstan

2020-09-30 06:58 UTC, XSAM approved these changes
Looks good. Thanks for your contribution.

2020-09-30 06:58 UTC, XSAM commented on CHANGELOG.md
> +- Added messaging operation semconv shortcut for `messaging.operation.send`
```suggestion
- Added messaging operation semconv shortcut for `messaging.operation.send`. (#1215)
```

2020-09-30 07:47 UTC, hstan commented
Thanks @XSAM I've fixed the CLA. 
However, the build is failing due to a seemingly flaky test, I don't have permission to rerun it.

2020-09-30 13:56 UTC, MrAlias requested changes
[The specification for messaging semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md#messaging-attributes) appears to explicitly state this value should not be set:

> If the operation is "send", this attribute MUST NOT be set, since the operation can be inferred from the span kind in that case.

Given that is the case we probably do not want to include this value here.

2020-09-30 18:08 UTC, Aneurysm9 approved these changes

2020-10-01 18:05 UTC, MrAlias commented
Closing due to the incompatibility with the specification.

2020-10-01 18:05 UTC, closed without merging