Call sampler on local child spans.
open-telemetry/opentelemetry-go pull request #1233
Opened 2020-10-08 22:29 UTC by paulosman

Fixes #1228 

Previously, the sampler would only be called for the first span in a process. This makes sense for trace level sampling but doesn't allow the sampler to specify attributes to be set on each span, which is important for some implementations. This change removes the guard that limits sampling decisions to local root spans.

2020-10-08 23:18 UTC, Aneurysm9 commented on CHANGELOG.md
> +- The Sampler is now called on local root spans. (#1228)
```suggestion
- The Sampler is now called on local child spans. (#1228)
```

2020-10-08 23:18 UTC, MrAlias approved these changes

2020-10-08 23:18 UTC, MrAlias commented on CHANGELOG.md
> +- The Sampler is now called on local root spans. (#1228)
```suggestion
- The Sampler is now called on local root spans. (#1233)
```

2020-10-08 23:23 UTC, Aneurysm9 approved these changes

2020-10-09 02:02 UTC, XSAM approved these changes

2020-10-09 17:25 UTC, MrAlias commented
@paulosman it looks like maintainer edits are turned off for this PR so I can't merge master into this. If you can do this sync this PR looks ready to merge.

2020-10-09 17:45 UTC, MrAlias commented on CHANGELOG.md
> +- The Sampler is now called on local child spans. (#1233)
We'll need to move this up to the `Unreleased` section.

2020-10-09 17:50 UTC, lizthegrey requested changes
please write tests for this.

2020-10-09 17:50 UTC, lizthegrey commented on CHANGELOG.md
> +- The Sampler is now called on local child spans. (#1233)
this goes under "changed" in "unreleased".

2020-10-09 22:07 UTC, paulosman commented
> please write tests for this.

Added a test to catch local child spans. Build is fixed, but circle seems stuck - pushed a changed and it won't rebuild.

2020-10-09 22:43 UTC, lizthegrey approved these changes

2020-10-09 22:48 UTC, merged