SpanFromContext returns nil if span not exists
open-telemetry/opentelemetry-go pull request #1255
Opened 2020-10-14 07:45 UTC by XSAM

Resolves #1251

Many places use a way to attain `SpanContext`, and it will panic if `SpanFromContext()` returns nil. 

```go
otel.SpanFromContext(ctx).SpanContext()
```

So, I add a new API `SpanContextFromContext` to replace that part without worry about panic.

2020-10-14 17:05 UTC, MrAlias approved these changes
:100:

2020-10-14 17:05 UTC, MrAlias commented on trace.go
> +// SpanContextFromContext returns the span context from ctx.
```suggestion
// SpanContextFromContext returns the current SpanContext from ctx, or an empty SpanContext if none set.
```

2020-10-15 16:46 UTC, Aneurysm9 requested changes
I'm not sure how I feel about this change.  Particularly with the addition of `SpanContextFromContext()` it seems like just moving things around.  It seems to me that the better experience is to have `SpanFromContext()` always return a usable span, even if it is no-op.  If an instrumentor is concerned with avoiding expensive operations for non-recording or no-op spans then the `span.IsRecording()` method is available to them.

2020-10-15 17:40 UTC, Aneurysm9 commented
After discussing this during the SIG meeting we came to the conclusion that adding `SpanContextFromContext()` is useful, but that `SpanFromContext()` should continue to return a `noopSpan{}`.  The `Span` API provides sufficient mechanisms for instrumentors to determine whether a given `Span` is recording and they should perform potentially expensive operations.

2020-10-16 07:09 UTC, XSAM commented
I don't understand the meaning that `SpanFromContext` returns `noopSpan` rather than nil.

In that situation, users can only invoke `IsRecording` to determine whether `Span` is active or not, but cannot determine whether the `Context` has `Span` or not.

I think users can easily use `span == nil` to determine the existence of `Span` if `SpanFromContext` returns nil. Also, it is quite common that gophers check whether the interface is nil before using it.

2020-10-16 15:03 UTC, Aneurysm9 commented
> I don't understand the meaning that `SpanFromContext` returns `noopSpan` rather than nil.
> 
> In that situation, users can only invoke `IsRecording` to determine whether `Span` is active or not, but cannot determine whether the `Context` has `Span` or not.

Looked at another way, what value does knowing whether the `Context` carries a `Span` provide?  If it is only to know that no valid span is active and that potentially expensive calculations can be avoided, `IsRecording()` provides the same capability and does not require `nil` checking.
 
> I think users can easily use `span == nil` to determine the existence of `Span` if `SpanFromContext` returns nil. Also, it is quite common that gophers check whether the interface is nil before using it.

It can be done, but it doesn't need to be done and it is a better DX to not require it be done.  Also, since it has not been required to this point we should assume that there is a significant body of code out there already that doesn't perform any such check and will be susceptible to runtime errors attempting to invoke methods on `nil` values.  This would be asking a significant remediation effort from all of our users for a questionable benefit for some of them.

2020-10-16 20:26 UTC, jmacd approved these changes

2020-10-16 20:28 UTC, jmacd commented
> that SpanFromContext() should continue to return a noopSpan{}

I agree with this statement, and was going to ask if it wouldn't be safer for SpanFromContext not to return nil.

2020-10-21 21:29 UTC, Aneurysm9 approved these changes

2020-10-21 21:30 UTC, merged