Enable support for externally-defined ID generators
open-telemetry/opentelemetry-go pull request #1363
Opened 2020-11-21 02:15 UTC by Aneurysm9

* Moved the SDK's `internal.IDGenerator` interface to the `sdk/trace`
package.
* Added `trace.WithIDGenerator()` `TracerProviderOption`.

2020-11-23 14:33 UTC, XSAM approved these changes

2020-11-23 15:37 UTC, krnowak requested changes

2020-11-23 15:37 UTC, krnowak commented on sdk/trace/id_generator.go
> +// IDGenerator allows custom generators for TraceId and SpanId.
```suggestion
// IDGenerator allows custom generators for TraceID and SpanID.
```

2020-11-23 15:37 UTC, krnowak commented on sdk/trace/id_generator.go
> +var _ IDGenerator = &defaultIDGenerator{}
How about renaming the `defaultIDGenerator` type to `randomIDGenerator`, and then renaming the `defIDGenerator` function as `defaultIDGenerator`?

2020-11-23 18:47 UTC, krnowak approved these changes

2020-11-24 09:04 UTC, jmacd commented
I made a note in the associated spec PR (https://github.com/open-telemetry/opentelemetry-specification/pull/1006#discussion_r520693556) that I'd probably rather see two methods, where one returns a single SpanID (taking a mutex once) and one returns a pair of TraceID and SpanID (taking a mutex once). What do you think?

2020-11-25 16:41 UTC, krnowak commented
> I made a note in the associated spec PR ([open-telemetry/opentelemetry-specification#1006 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/1006#discussion_r520693556)) that I'd probably rather see two methods, where one returns a single SpanID (taking a mutex once) and one returns a pair of TraceID and SpanID (taking a mutex once). What do you think?

Sounds useful as this seems to be how the ID generator is going to be used. Would there be a case where we only wanted to generate a trace ID?

2020-12-03 20:42 UTC, MrAlias commented
> I made a note in the associated spec PR ([open-telemetry/opentelemetry-specification#1006 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/1006#discussion_r520693556)) that I'd probably rather see two methods, where one returns a single SpanID (taking a mutex once) and one returns a pair of TraceID and SpanID (taking a mutex once). What do you think?

Yeah, I think this is indeed going to be how this will be used.

> Would there be a case where we only wanted to generate a trace ID?

I feel like that would be the corner case anyway so throwing away that returned value wouldn't be too much of an issue.

2020-12-03 20:47 UTC, MrAlias commented on sdk/trace/id_generator.go
> +	NewSpanID() trace.SpanID
I like @jmacd's idea of having these be a function that returns a span ID and a trace ID with a span ID. I also wonder if we can include arguments that would be helpful for ID generation. Maybe something like:

```suggestion
	NewIDs(ctx context.Context) (trace.TraceID, trace.SpanID)
	NewSpanID(ctx context.Context, traceID trace.TraceID) trace.SpanID
```

I think passing a context will enable generation with the context of things like baggage or other vendor defined values. Also, passing the trace ID to the NewSpanID method might be a useful things if a generator uses that in relation to the span IDs it generates.

2020-12-08 18:17 UTC, dashpole approved these changes

2020-12-08 19:15 UTC, MrAlias approved these changes

2020-12-09 07:47 UTC, krnowak approved these changes
One nit, otherwise looks good.

2020-12-09 07:47 UTC, krnowak commented on sdk/trace/id_generator.go
> +// randomly-chosen sequence. mu should be held while this function is called.
I'd drop the comment about `mu`. Mutex is now embedded, but I don't think that anyone should care about this implementation detail.

```suggestion
// randomly-chosen sequence.
```

2020-12-10 01:30 UTC, merged