Add `ExportTimeout` option to batch span processor
open-telemetry/opentelemetry-go pull request #1755
Opened 2021-03-30 09:23 UTC by matej-g

Adding `ExportTimeout` option to batch span processor, in order to make it comply with the specification ([relevant part](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#batching-processor)). Cancellation of the export should be achieved by passing a context with deadline to the exporter's method.

Resolves #1613

2021-03-30 17:08 UTC, MrAlias approved these changes

2021-03-30 17:44 UTC, Aneurysm9 approved these changes

2021-03-31 12:07 UTC, XSAM approved these changes

2021-03-31 15:04 UTC, MrAlias requested changes

2021-03-31 16:50 UTC, MrAlias commented on sdk/trace/batch_span_processor_test.go
> +			name: "non-default ExportTimeout",
Something similar to [this](https://github.com/open-telemetry/opentelemetry-go/pull/1758/files#diff-6b76a7df46dd00e7cfa0858e9f2a3ecbbec18a6cfe7349d9b1814863f21c0bb4R141-R145) perhaps?

2021-04-05 10:21 UTC, matej-g commented on sdk/trace/batch_span_processor_test.go
> +			name: "non-default ExportTimeout",
Thanks for catching this :+1:, I introduced some artificial delay on that test case, checks seem to be passing now.

2021-04-05 17:13 UTC, MrAlias approved these changes

2021-04-05 17:38 UTC, merged