Adds a custom MarshalJSON method for trace.Link
open-telemetry/opentelemetry-go pull request #1852
Opened 2021-04-27 16:44 UTC by IrisTuntun

Adds a custom MarshalJSON method for `trace.Link` to marshal all fields.
Should resolve #1820

2021-04-27 17:03 UTC, MrAlias reviewed
Should we just not embed the `SpanContext` in a `Link`? Instead make it a field?

2021-04-27 17:14 UTC, IrisTuntun commented
> Should we just not embed the `SpanContext` in a `Link`? Instead make it a field?

Then it will be another issue. I wonder if I should make the change in this PR.

2021-04-27 18:28 UTC, MrAlias commented
> Then it will be another issue. I wonder if I should make the change in this PR.

I would get the opinion of another approver/maintainer before restarting.

2021-04-27 18:29 UTC, MrAlias requested changes

2021-04-27 18:29 UTC, MrAlias commented on CHANGELOG.md
> -- - Extract resource attributes from the `OTEL_RESOURCE_ATTRIBUTES` environment variable and merge them with the `resource.Default` resource as well as resources provided to the `TracerProvider` and
This CHANGELOG is not properly merged. It needs to be sync-ed with main and only contain the changes relevant to this PR.

2021-04-29 17:56 UTC, Aneurysm9 commented
> Should we just not embed the `SpanContext` in a `Link`? Instead make it a field?

That would also work.  I don't have any context for why `SpanContext` was embedded rather than included as a field, but I'd presume that it was to avoid the need to write passthrough methods to get at the linked trace and span IDs.  That said, it doesn't look like the spec provides for any sort of interface for interacting with `Link`s and API `Span`s are write-only, so once they're added there's no way to access their properties through the API.

As I was reviewing #1846 I was wondering whether the `Link` type should be moved as well.  It would be slightly more complicated since the API does have a `Span#AddLink()` method, but the spec certainly contemplates that taking separate `SpanContext` and `Attributes` arguments, so we could restructure.

2021-04-29 18:25 UTC, Aneurysm9 commented
I see I didn't look closely enough at the issue #1846 was addressing and this topic is discussed there.  Added some thoughts: https://github.com/open-telemetry/opentelemetry-go/issues/1845#issuecomment-829487787.

2021-04-29 23:07 UTC, MrAlias commented
Closing as the decision outlined in https://github.com/open-telemetry/opentelemetry-go/issues/1845#issuecomment-829594030 is to remove the `Link` type from the API. We can recreate the type in the SDK without embedding the `SpanContext`.

2021-04-29 23:07 UTC, closed without merging

2021-04-30 15:59 UTC, MrAlias commented
@IrisTuntun we realized that we cannot remove the link and we should instead go with the un-embed solution: https://github.com/open-telemetry/opentelemetry-go/issues/1845#issuecomment-829700761

Is this something you would like to open a PR for?

2021-04-30 16:19 UTC, IrisTuntun commented
> @IrisTuntun we realized that we cannot remove the link and we should instead go with the un-embed solution: [#1845 (comment)](https://github.com/open-telemetry/opentelemetry-go/issues/1845#issuecomment-829700761)
> 
> Is this something you would like to open a PR for?

Sure, I can take this. Will open a PR for it.