support zipkin exporter endpoint env
open-telemetry/opentelemetry-go pull request #2490
Opened 2022-01-01 21:58 UTC by yeya24

Signed-off-by: Ben Ye <ben.ye@bytedance.com>

Fixes #2309.

This pr adds support of reading env `OTEL_EXPORTER_ZIPKIN_ENDPOINT` to specify zipkin endpoint. If empty collector endpoint is provided, then the default collector address will be used mentioned in https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/sdk-environment-variables.md#zipkin-exporter

2022-01-03 17:02 UTC, Aneurysm9 requested changes

2022-01-03 17:02 UTC, Aneurysm9 commented on exporters/zipkin/zipkin.go
> +func New(opts ...Option) (*Exporter, error) {
While I think I would prefer this interface, this module is stable at v1.3.0 and we cannot change its interface in this way.  What about just removing the error if `collectorURL` is empty?

2022-01-03 22:40 UTC, Aneurysm9 approved these changes

2022-01-04 15:03 UTC, dashpole approved these changes

2022-01-05 01:13 UTC, yeya24 commented
Just fix the conflict on the changelog. Is it good to merge now?

2022-01-05 02:49 UTC, Aneurysm9 commented
Please fix the lint issue, then this should be ready to merge.

2022-01-05 04:29 UTC, XSAM approved these changes

2022-01-06 16:28 UTC, merged

2022-01-07 19:01 UTC, jcchavezs commented on exporters/zipkin/zipkin.go
> +		collectorURL = envOr(envEndpoint, defaultCollectorURL)
If we are overriding this, shall we add a info log explaining where this come from?