chore: add logging example
open-telemetry/opentelemetry-go pull request #2962
Opened 2022-06-19 14:27 UTC by lyl156

It is PR for issue#2238.   
How could I fix  
```
license header checking failed:
./example/logging/build.sh
./example/logging/main.go
make: *** [license-check] Error 1 
```
after `make precommit`.  
How to sign CLA mentioned in `CONTRIBUTING.md`?

2022-06-20 01:57 UTC, hanyuancheung commented on example/logging/README.md
> +Now you can check the trace data generated by `main.go` on the terminal where you type `sh build.sh`.
Pls fix the markdown format.

2022-06-20 02:49 UTC, lyl156 commented on example/logging/README.md
> +Now you can check the trace data generated by `main.go` on the terminal where you type `sh build.sh`.
fixed

2022-06-21 02:24 UTC, lyl156 reviewed
CI is not clear now. 

Should I pull this and re-submit again?
Or is there something I can do to clear the CI?

2022-06-21 02:43 UTC, hanyuancheung commented
> CI is not clear now.
> 
> Should I pull this and re-submit again? Or is there something I can do to clear the CI?

rerun `make precommit` command before committing the code.

2022-06-21 11:20 UTC, lyl156 commented
> > CI is not clear now.
> > Should I pull this and re-submit again? Or is there something I can do to clear the CI?
> 
> rerun `make precommit` command before committing the code.

2022-06-21 11:35 UTC, lyl156 commented
reopen it

2022-06-21 17:17 UTC, MrAlias requested changes
This PR adds an example of how to use the logging exporter for the collector. The linked issue this PR says it addresses is one that looks to refactor the existing collector example, not add another one with a different exporter. I do not see the value in accepting these changes, it does not add a unique example of how to use this project. I would recommend it is closed.

2022-06-22 07:38 UTC, dmathieu commented
I think naming this example `logger` is misleading. It may look like the example is about using the library to do logging.
I also agree with @MrAlias that we don't need a new example if one is too complicated. The existing example should be simplified, or refactored to be more understandable (for example with steps of increasing complexity).

2022-06-24 21:18 UTC, MrAlias commented
> I think naming this example `logger` is misleading. It may look like the example is about using the library to do logging. I also agree with @MrAlias that we don't need a new example if one is too complicated. The existing example should be simplified, or refactored to be more understandable (for example with steps of increasing complexity).

@lyl156 is this something you are willing to consider?

2022-06-25 01:38 UTC, lyl156 commented
> 
What I can do now is to replace the original with mine, because I don't understand your exact thoughts on this issue. 
If you can provide exact examples representing the result you want, I'd love to revise this pr.
If not, I will close this pr soon.

2022-06-27 12:02 UTC, closed without merging