Rename Package sdk/metric/export into sdk/metric/metricdata
open-telemetry/opentelemetry-go pull request #3014
Opened 2022-07-13 02:20 UTC by hanyuancheung

Follow: #3013 
Rename Package sdk/metric/export into sdk/metric/metricdata .

2022-07-13 11:21 UTC, MadVikingGod requested changes
You won't be able to find and replace just using the word `export`, as that breaks a number of comments.  I would suggest maybe trying to find `"go.opentelemetry.io/otel/sdk/metric/export"` and `export.`, while double-checking comments.

Also this won't be accepted with all the changes to the go.mod files, I think you might be on an older version of the cross-link tool.

2022-07-13 11:21 UTC, MadVikingGod commented on bridge/opentracing/go.mod
> +replace go.opentelemetry.io/otel/example/namedtracer => ../../example/namedtracer
Where did these changes come from?

2022-07-13 15:45 UTC, MrAlias approved these changes

2022-07-13 16:03 UTC, MadVikingGod approved these changes

2022-07-14 12:01 UTC, MrAlias commented
This looks ready to merge, please update with the base branch and resolve conflicts so we can do so.

2022-07-14 12:24 UTC, MadVikingGod commented
Also, note that #3017 added a number of new uses of export.  Those should be updated in this patch accordingly.

2022-07-14 12:59 UTC, hanyuancheung commented
> This looks ready to merge, please update with the base branch and resolve conflicts so we can do so.

Already rebased conflict. Pls help to merge this.

2022-07-14 19:32 UTC, merged