Add an example of view
open-telemetry/opentelemetry-go pull request #3177
Opened 2022-09-16 08:21 UTC by tony612

Add an example of custom histogram buckets and renaming in prometheus. See https://github.com/open-telemetry/opentelemetry-go/issues/689

2022-09-16 08:28 UTC, dmathieu commented
I wonder if we shouldn't keep the base example simple, to not confuse folks who just get started. How about adding a new example instead of extending the current one?

2022-09-16 08:36 UTC, tony612 commented
@dmathieu How about moving it to a new example `view` to demo how to use view? Cc @MrAlias

2022-09-16 08:43 UTC, XSAM commented
> @dmathieu How about moving it to a new example `view` to demo how to use view? Cc @MrAlias

That would be good. 👍

2022-09-19 03:24 UTC, XSAM commented on example/view/main.go
> +const meterName = "github.com/open-telemetry/opentelemetry-go/example/prometheus"
```suggestion
const meterName = "github.com/open-telemetry/opentelemetry-go/example/view"
```

2022-09-19 03:49 UTC, XSAM approved these changes

2022-09-19 07:59 UTC, dmathieu approved these changes

2022-09-19 16:59 UTC, MrAlias requested changes
Having this as a new module means it needs to be included in our dependabot config (should happen if you run `make`) and `versions.yaml`.

2022-09-22 03:07 UTC, tony612 commented
@MrAlias Please review again. Thanks.

2022-09-22 16:11 UTC, MrAlias reviewed
Please add a changelog entry

2022-09-22 16:11 UTC, MrAlias commented on example/view/main.go
> +	}
Note, this shouldn't be needed. Tracking resolution with https://github.com/open-telemetry/opentelemetry-go/issues/3224

2022-09-26 15:57 UTC, MrAlias approved these changes

2022-09-26 16:04 UTC, merged