Return pointer to View func
open-telemetry/opentelemetry-go pull request #3221
Opened 2022-09-22 08:28 UTC by jyz0309

Signed-off-by: jyz0309 <45495947@qq.com>

2022-09-22 09:51 UTC, dmathieu approved these changes

2022-09-22 14:35 UTC, MrAlias requested changes
Please add a changelog entry for this.

2022-09-22 14:35 UTC, MrAlias commented on sdk/metric/view/view.go
>  func New(opts ...Option) (View, error) {
```suggestion
func New(opts ...Option) (*View, error) {
```

2022-09-22 17:00 UTC, jmacd commented
I'd like to see which benchmarks improve with this PR before and after, since the motivation for this change is based on performance.

2022-09-23 11:00 UTC, jyz0309 commented
> I'd like to see which benchmarks improve with this PR before and after, since the motivation for this change is based on performance.

Ok, I will make a benchmark for it this weekend. : )

2022-10-07 15:14 UTC, jyz0309 commented
> I'd like to see which benchmarks improve with this PR before and after, since the motivation for this change is based on performance.

I have made a small benchmark for View.New() function.
```
BenchmarkViewPointer/View.New
BenchmarkViewPointer/View.New-8         	1000000000	         0.0000240 ns/op
BenchmarkViewPointer/View.New_without_pointer
BenchmarkViewPointer/View.New_without_pointer-8         	1000000000	         0.0000252 ns/op
``` 
It seems that the benefit is very small :( I will close this PR later.

2022-10-11 02:52 UTC, closed without merging