Document compatibility between modules
open-telemetry/opentelemetry-go pull request #3806
Opened 2023-02-27 13:38 UTC by pellared

Documents https://github.com/open-telemetry/opentelemetry-go/issues/3548

2023-02-27 16:06 UTC, MrAlias reviewed
Overall looks good. Thanks for adding this.

2023-02-27 16:06 UTC, MrAlias commented on VERSIONING.md
> +  modules released from the same commit. For example,
It should be clear here that we are talking cross module compatibility by using the term "other modules" and we want to guarantee across the release not a commit.

```suggestion
* Go modules are only guaranteed to be compatible with
  other modules from the same release. They are not
  guaranteed to be compatible with other modules from
  previous releases.  For example,
```

2023-02-27 16:06 UTC, MrAlias commented on VERSIONING.md
> +  [#3548](https://github.com/open-telemetry/opentelemetry-go/issues/3548).
I don't think it is necessary to include an issue link here. The git blame will show this PR which links to the origin if a dev needs to know.

```suggestion
```

2023-02-27 16:23 UTC, Aneurysm9 requested changes
I'm not sure this is the correct approach here.  I understand it is what we have done to this point and expect to continue doing, but I think it is in conflict with [the specification's versioning guidelines](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md#design-goals).

> Never create a dependency conflict between packages which rely on different versions of OpenTelemetry.

It is possible (maybe even likely) that an instrumentation library will require a newer version of the OTel API while the application still requires an older version of the SDK.  This puts the user in the position of needing to choose between updating an instrumented dependency or staying on a known-working version of the SDK.

What options do we have for avoiding this coupling?  I think mutual dependencies from the API back to the SDK modules that depend on its internal packages is a non-starter.  What about managed duplication through code generation?  Are there other approaches we could take?

2023-02-27 18:01 UTC, pellared commented
> What about managed duplication through code generation?

That is exactly what I propose [here](https://github.com/open-telemetry/opentelemetry-go/issues/3548#issuecomment-1443172592) 

> We could address the problem e.g. by using "code generation" to "copy/paste" the common code that is shared between modules.

Having that said, I think we should document the current state before we address the issue.

2023-02-28 14:29 UTC, ericklaus-wf commented
I think the situation is more complicated than described in this documentation update. It isn't the case that modules are only compatible at the same version (`go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.11.1` is only compatible with `go.opentelemetry.io/otel v1.11.1`). Instead, modules are only guaranteed compatible at releases _from the same commit_, which _may be different versions_.

For example, `go.opentelemetry.io/otel/exporters/otlp/otlpmetric@v0.32.1` is compatible with `go.opentelemetry.io/otel@v1.11.1` but is not compatible with `go.opentelemetry.io/otel@v1.11.2`. The only way to discover compatible versions is to manually inspect each git tag, looking for tags at the same commit. That feels like a pretty onerous burden, but documenting it here will at least make it clearer to your integrators what they're signing up for.

2023-03-02 18:55 UTC, MadVikingGod commented
@pellared I did a bit of work to identify which modules take dependencies on cross-module `internal` packages [here](https://github.com/open-telemetry/opentelemetry-go/issues/3548#issuecomment-1452106454).

2023-03-02 19:04 UTC, pellared commented
Closing. I assigned https://github.com/open-telemetry/opentelemetry-go/issues/3548 to myself.

2023-03-02 19:04 UTC, closed without merging

2023-03-02 19:06 UTC, pellared commented
> I think the situation is more complicated than described in this documentation update. It isn't the case that modules are only compatible at the same version (`go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.11.1` is only compatible with `go.opentelemetry.io/otel v1.11.1`). Instead, modules are only guaranteed compatible at releases _from the same commit_, which _may be different versions_.
> 
> For example, `go.opentelemetry.io/otel/exporters/otlp/otlpmetric@v0.32.1` is compatible with `go.opentelemetry.io/otel@v1.11.1` but is not compatible with `go.opentelemetry.io/otel@v1.11.2`. The only way to discover compatible versions is to manually inspect each git tag, looking for tags at the same commit. That feels like a pretty onerous burden, but documenting it here will at least make it clearer to your integrators what they're signing up for.

Correct. https://github.com/open-telemetry/opentelemetry-go/pull/3806/commits/cf20bc3bbfc289b93478215f580306223fe99781 😉