fix: set withinsecure() by default in otlp_http_example
open-telemetry/opentelemetry-go pull request #4682
Opened 2023-10-31 03:21 UTC by rfyiamcool

### summary 

I think the default configuration `Insecure` would be better.

When I tested it yesterday, I found that it always prompted https issues. I found out through the code that https is enabled by default. Usually the collector does not enable https security.

When people learn how to use otel through examples, it is easy to misunderstand.

Of course, this is just personal advice. 😁

```
otel  http: server gave HTTP response to HTTPS client
otel  http: server gave HTTP response to HTTPS client
otel  http: server gave HTTP response to HTTPS client
```

2023-10-31 06:37 UTC, pellared requested changes
Thank you for your contribution. However, we cannot accept this change as it would be breaking. See more: https://github.com/open-telemetry/opentelemetry-go/issues/4147

EDIT: Sorry, I have not noticed that this is a change in a test example.

2023-11-01 14:32 UTC, arukiidou commented
> Thank you for your contribution. However, we cannot accept this change as it would be breaking. See more: #4147
@pellared 

- I have a different opinion
  - example_test will never be the default behavior
  - example_test will not a production environment

2023-11-01 18:57 UTC, dmathieu commented
Even outside the breaking change, I don't know if setting `WithInsecure` here is so good.
It's something someone should only be using for dev/testing environments, never in production. And this example here is a runnable example, but not a "getting started" one where we show off how things work using a dummy environment (the example [here])(https://github.com/open-telemetry/opentelemetry-go/tree/main/example/otel-collector) is that).

So I agree with @pellared that this change needn't be merged, not necessarily because of the breaking change but rather because the example doesn't need it per-se.

2023-11-02 06:18 UTC, pellared commented
Sorry, I have not noticed that this is just an example 🤦 

I will look at making better documentation as part of https://github.com/open-telemetry/opentelemetry-go/issues/4147.

2023-11-06 09:33 UTC, closed without merging