fix: Fix stdouttrace/example_test to make the trace_id same.
open-telemetry/opentelemetry-go pull request #4855
Opened 2024-01-27 07:46 UTC by StLeoX

2024-01-27 07:56 UTC, StLeoX commented
/easycla

2024-01-29 18:36 UTC, MrAlias requested changes

2024-01-29 18:36 UTC, MrAlias commented on exporters/stdout/stdouttrace/example_test.go
> +	semconv "go.opentelemetry.io/otel/semconv/v1.21.0"
Do not downgrade the semconv used here.

2024-01-29 18:36 UTC, MrAlias commented on exporters/stdout/stdouttrace/example_test.go
> +func TestExample(t *testing.T) {
This transforms the example test into a test. The name should not be modified.

https://go.dev/blog/examples

2024-01-29 18:37 UTC, MrAlias commented
Please be sure to sign the CLA so these changes can be considered.

2024-01-30 02:30 UTC, StLeoX commented
/easycla

2024-01-30 17:19 UTC, merged

2024-01-30 17:21 UTC, pellared requested changes

2024-01-30 17:21 UTC, pellared commented on exporters/stdout/stdouttrace/example_test.go
> +	ctx, ans = add(ctx, ans, 2)
I find returning a `ctx` pretty unusual (code smell). Why not creating a parent span like:



```suggestion
	ctx, span = tracer.Start(ctx, "Calculation")
	defer span.End()
	ans := multiply(ctx, 2, 2)
	ans = multiply(ctx, ans, 10)
	ans = add(ctx, ans, 2)
```