[chore]: enable negative-positive rule from testifylint
open-telemetry/opentelemetry-go pull request #5849
Opened 2024-09-26 19:14 UTC by mmorel-35

#### Description

Testifylint is a linter that provides best practices with the use of testify.

This PR enables  [negative-positive](https://github.com/Antonboom/testifylint?tab=readme-ov-file#negative-positive) rule from [testifylint](https://github.com/Antonboom/testifylint)

2024-09-26 19:31 UTC, dmathieu approved these changes

2024-09-27 06:44 UTC, pellared requested changes
It looks like `assert.Equal` is correct in almost all places (except one).

2024-09-27 06:44 UTC, pellared commented on exporters/prometheus/exporter_test.go
> +			require.InDelta(t, tc.expectedExemplarValue, exemplar.GetValue(), 0.01)
require.Equal is fine here as the exemplar value will be always exactly the same (it is set by a single recording call)

2024-09-27 06:44 UTC, pellared commented on log/keyvalue_test.go
> +		assert.InDelta(t, val, v.AsFloat64(), 0.01, "AsFloat64")
It will be exactly the same - this is  just transformation. If there would be a "delta" then I think it would be even a bug.

2024-09-27 06:44 UTC, pellared commented on log/keyvalue_test.go
> +	assert.InDelta(t, 0.0, testing.AllocsPerRun(runs, func() {
`testing.AllocsPerRun` always returns an integer. It is documented and the Go standard library in its unit tests also always compares its result with a constant value. See https://github.com/search?q=repo%3Agolang%2Fgo%20AllocsPerRun&type=code

2024-09-27 06:44 UTC, pellared commented on metric/asyncfloat64_test.go
> +			assert.InDelta(t, token, o.got, 0.01, "callback not set")
The value should be equal. It is set via a single observation.

2024-09-27 06:44 UTC, pellared commented on sdk/metric/aggregation_test.go
> +	assert.InDelta(t, orig, cpH.Boundaries[0], 0.01, "changing the underlying slice data should not affect the copy")
The boundary is set directly

2024-09-27 06:44 UTC, pellared commented on sdk/metric/internal/aggregate/exponential_histogram_test.go
> +			assert.InDelta(t, tt.expected.min, dp.min, 0.01)
The values are set based on input

2024-09-27 06:44 UTC, pellared commented on sdk/metric/internal/aggregate/exponential_histogram_test.go
> +			assert.InDelta(t, tt.expected.sum, dp.sum, 0.01)
I think that it is the only place where `assert.InDelta` is needed 😉

2024-09-27 06:44 UTC, pellared commented on sdk/metric/internal/exemplar/value_test.go
These are conversions so there should be no error.

2024-09-27 08:56 UTC, pellared commented
> @pellared ,
> 
> I believ it's probably better to keep float-compare disabled in that case. What do you think ?

Agree

2024-09-27 19:11 UTC, pellared approved these changes

2024-09-30 06:44 UTC, merged